### ISSUE TITLE
Whitelisting random IDs?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [SpoostyGuy/WhitelistQueue#2]
When I look at the logs for the app, it says it adds the correct id into the queue but then it says it whitelisted some random ID? 
![image](https://user-images.githubusercontent.com/54049600/189560101-cbbf9398-b712-4f67-8a38-88a38e5ffb19.png)
What is the cause behind this weird glitch?

**Comment by SpoostyGuy** [comment]
Both are the same product, they just have different id's
The first log shows the asset id
The second log shows the product id
I can assure you that both are the same product
I will get around to fixing this soon

**Comment by SpoostyGuy** [comment]
If you check your inventory, it should show the concrete wall or whatever model you put

**Comment by SpoostyGuy** [comment]
I just released a patch that fixes this bug, gonna close this issue
